In [1]:
#Dependencies
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import datetime
import statsmodels.formula.api as sm

#Constants
data_file = "Zillow_pivot_cleaned.csv"
label_file = "Phoenix_Zillow_Codes.xlsx"

In [2]:
# Take in all of employment and unemployment data and read it into pandas
phoenix_employment = "Resources/phoenix_employment.csv"
phoenix_unemployment = "Resources/phoenix_unemployment.csv"

phoenix_em_df = pd.read_csv(phoenix_employment, index_col=0)
phoenix_un_df = pd.read_csv(phoenix_unemployment, index_col=0)

phoenix_em_df 
phoenix_un_df

,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
Year,,,,,,,,,,,,
1999,1578066,1584222,1585224,1580055,1588296,1596756,1604886,1595958,1600052.0,1604937.0,1614940.0,1622822.0
2000,1593471,1602769,1599895,1607478,1598814,1610811,1605966,1606272,1620675.0,1627557.0,1633557.0,1647067.0
2001,1636850,1648610,1651014,1649485,1647023,1650118,1654691,1642867,1659968.0,1668426.0,1667790.0,1673006.0
2002,1654868,1675135,1675100,1678397,1680127,1688556,1689100,1694967,1707218.0,1708424.0,1710633.0,1709692.0
2003,1697363,1710594,1712821,1724357,1725624,1736581,1729695,1729691,1736622.0,1749473.0,1762317.0,1765233.0
2004,1753874,1762375,1762380,1769489,1772710,1783492,1796584,1790883,1796539.0,1812156.0,1821557.0,1824292.0
2005,1814437,1822286,1827021,1844704,1849858,1860494,1870868,1875603,1882879.0,1898907.0,1905650.0,1909234.0
2006,1901250,1913561,1922139,1928931,1936819,1946039,1953536,1958179,1966730.0,1984257.0,1988557.0,1993927.0
2007,1975145,1978324,1983747,1977695,1980485,1990231,1989870,1986239,1996647.0,1997239.0,2006408.0,1999262.0
2008,1993471,1991054,1988239,1989849,1979651,1978204,1965921,1966181,1971910.0,1978295.0,1973787.0,1958144.0
2009,1929842,1928190,1918768,1923204,1908015,1903307,1893012,1878273,1875567.0,1875513.0,1883069.0,1866026.0
2010,1869615,1874869,1878510,1892588,1880880,1873990,1863136,1863279,1870834.0,1873228.0,1873822.0,1873316.0
2011,1861415,1865691,1873061,1874253,1868695,1855523,1847043,1850762,1864723.0,1876642.0,1885736.0,1887097.0
2012,1874555,1885876,1891035,1891991,1890486,1886259,1878124,1880089,1903003.0,1913210.0,1913745.0,1914778.0
2013,1901053,1911346,1912337,1916742,1916595,1912777,1904422,1906027,1924789.0,1919452.0,1944685.0,1946512.0
2014,1953341,1964689,1982414,1980626,1978109,1981287,1975893,1982457,2003395.0,2021500.0,2035751.0,2033919.0
2015,2034569,2045728,2050610,2056049,2060911,2057488,2058016,2062225,2073948.0,2087268.0,2101642.0,2101329.0
2016,2105712,2123264,2131239,2124317,2127634,2126152,2132749,2137298,2154421.0,2162529.0,2180458.0,2172226.0
2017,2174954,2193379,2203637,2208570,2202374,2208812,2215506,2215958,2244514.0,2240720.0,2259862.0,2252445.0
2018,2254317,2282747,2288154,2286777,2291580,2292952,2306538,2297320,2327702.0,2338006.0,2357448.0,2354244.0
2019,2347408,2366730,2361436,2359228,2365751,2391380,2392982,2389376,NaN,NaN,NaN,NaN

In [4]:
# Covert the employment data to the same format with unemployment data, then add two dataframe together.

df_em=phoenix_em_df.multiply(1000)


df_em

,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
Year,,,,,,,,,,,,
1999,1478800.0,1502200.0,1512000.0,1521900.0,1521800.0,1513300.0,1503900.0,1512400.0,1536500.0,1548800.0,1563200.0,1576100.0
2000,1533600.0,1557400.0,1569600.0,1572400.0,1582600.0,1563600.0,1544300.0,1563900.0,1591800.0,1602100.0,1615900.0,1631000.0
2001,1581200.0,1605900.0,1616800.0,1611100.0,1607100.0,1588700.0,1565800.0,1583300.0,1598000.0,1601000.0,1602900.0,1606700.0
2002,1567200.0,1582200.0,1593600.0,1606500.0,1602500.0,1590800.0,1563400.0,1586700.0,1598400.0,1609700.0,1633600.0,1632800.0
2003,1588600.0,1607800.0,1616200.0,1622700.0,1624800.0,1606500.0,1584100.0,1611100.0,1623700.0,1644500.0,1658600.0,1669700.0
2004,1628200.0,1650000.0,1664200.0,1678700.0,1680900.0,1666200.0,1656500.0,1677200.0,1696700.0,1726800.0,1742600.0,1758600.0
2005,1716500.0,1744700.0,1760500.0,1785100.0,1787200.0,1770500.0,1763800.0,1790000.0,1818700.0,1827200.0,1850000.0,1862400.0
2006,1831400.0,1863900.0,1881200.0,1885100.0,1893200.0,1873500.0,1856700.0,1881700.0,1902800.0,1910100.0,1924400.0,1931900.0
2007,1884800.0,1911200.0,1924000.0,1917200.0,1922300.0,1901900.0,1885100.0,1914300.0,1925700.0,1935300.0,1946700.0,1947700.0
2008,1900900.0,1912800.0,1909700.0,1900800.0,1894100.0,1855200.0,1822300.0,1853200.0,1858000.0,1852600.0,1849700.0,1837200.0
2009,1777000.0,1772400.0,1765000.0,1751100.0,1738900.0,1694300.0,1671200.0,1683800.0,1695900.0,1703700.0,1715900.0,1716100.0
2010,1676700.0,1689300.0,1699400.0,1704400.0,1708600.0,1664800.0,1647500.0,1670100.0,1681600.0,1705900.0,1723000.0,1728300.0
2011,1692900.0,1707900.0,1718200.0,1727000.0,1724000.0,1680000.0,1665300.0,1702100.0,1724800.0,1738500.0,1758400.0,1761900.0
2012,1731500.0,1746100.0,1758900.0,1760100.0,1757700.0,1726900.0,1706900.0,1746900.0,1768600.0,1785900.0,1809400.0,1817200.0
2013,1779100.0,1797200.0,1806800.0,1812400.0,1810700.0,1776500.0,1761300.0,1798100.0,1816600.0,1838000.0,1864800.0,1869700.0
2014,1827500.0,1842100.0,1849300.0,1854600.0,1843000.0,1812600.0,1796200.0,1837200.0,1855400.0,1883300.0,1907800.0,1918600.0
2015,1878600.0,1896900.0,1902200.0,1910700.0,1904100.0,1870700.0,1864900.0,1900000.0,1922500.0,1956300.0,1981600.0,1984600.0
2016,1944900.0,1965900.0,1972800.0,1982000.0,1971200.0,1932000.0,1931800.0,1968700.0,1994800.0,2013400.0,2033500.0,2036800.0
2017,1999600.0,2019600.0,2027700.0,2040100.0,2028600.0,2003600.0,1988600.0,2028200.0,2051600.0,2076300.0,2101700.0,2105000.0
2018,2069500.0,2093200.0,2101200.0,2101300.0,2094500.0,2061800.0,2056900.0,2102800.0,2122500.0,2145100.0,2169300.0,2169500.0
2019,2135100.0,2155400.0,2160100.0,2166500.0,2159200.0,2126500.0,2117700.0,2160400.0,NaN,NaN,NaN,NaN

In [ ]:
employe_rate, = plt.plot(Year, df_emrate.loc['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], color="")