In [1]:
#Import Dependencies
import requests
import pandas as pd
import quandl

#Get Quandl API key
quandl.read_key()
api_key = quandl.ApiConfig.api_key

In [2]:
def make_url(code):
    return f"https://www.quandl.com/api/v3/datasets/ZILLOW/{code}.json?api_key={api_key}"

In [3]:
#Get Zillow codes
zillow_codes_file = "Phoenix_Zillow_Codes.xlsx"
Zillow_data_df = pd.read_excel(zillow_codes_file)
codesdf = Zillow_data_df.loc[:,["code","description"]]
codesdf["url"] = codesdf["code"].apply(make_url)
codesdf

,code,description,url
0,C36159_BSICG,median market value of buyer seller index cross,https://www.quandl.com/api/v3/datasets/ZILLOW/...
1,C36159_BSICT,median market value of buyer seller index cros...,https://www.quandl.com/api/v3/datasets/ZILLOW/...
2,C36159_DOZ,median market value of days on zillow,https://www.quandl.com/api/v3/datasets/ZILLOW/...
3,C36159_FOR10K,"median market value of foreclosures per 10,000...",https://www.quandl.com/api/v3/datasets/ZILLOW/...
4,C36159_MDLNSAH,median market value of median daily listings -...,https://www.quandl.com/api/v3/datasets/ZILLOW/...
5,C36159_MDLSAAH,median market value of median daily listings -...,https://www.quandl.com/api/v3/datasets/ZILLOW/...
6,C36159_MLNSAH,median market value of monthly listings - nsa ...,https://www.quandl.com/api/v3/datasets/ZILLOW/...
7,C36159_MLSAAH,median market value of monthly listings - sa -...,https://www.quandl.com/api/v3/datasets/ZILLOW/...
8,C36159_MTURN,median market value of monthly turnover,https://www.quandl.com/api/v3/datasets/ZILLOW/...
9,C36159_NMLNSAH,median market value of new monthly listings - ...,https://www.quandl.com/api/v3/datasets/ZILLOW/...
10,C36159_NMLSAAH,median market value of new monthly listings - ...,https://www.quandl.com/api/v3/datasets/ZILLOW/...
11,C36159_SC,median market value of sales counts,https://www.quandl.com/api/v3/datasets/ZILLOW/...
12,C36159_SCBT,median market value of sales counts - bottom tier,https://www.quandl.com/api/v3/datasets/ZILLOW/...
13,C36159_SCMT,median market value of sales counts - middle tier,https://www.quandl.com/api/v3/datasets/ZILLOW/...
14,C36159_SCSA,median market value of sales counts - sa,https://www.quandl.com/api/v3/datasets/ZILLOW/...
15,C36159_SCSABT,median market value of sales counts - sa - bot...,https://www.quandl.com/api/v3/datasets/ZILLOW/...
16,C36159_SCSAMT,median market value of sales counts - sa - mid...,https://www.quandl.com/api/v3/datasets/ZILLOW/...
17,C36159_SCSATT,median market value of sales counts - sa - top...,https://www.quandl.com/api/v3/datasets/ZILLOW/...
18,C36159_SCTT,median market value of sales counts - top tier,https://www.quandl.com/api/v3/datasets/ZILLOW/...
19,C36159_SP,median market value of sales prices,https://www.quandl.com/api/v3/datasets/ZILLOW/...
20,C36159_SPBT,median market value of sales counts - bottom tier,https://www.quandl.com/api/v3/datasets/ZILLOW/...
21,C36159_SPFS,median market value of sales previously forecl...,https://www.quandl.com/api/v3/datasets/ZILLOW/...
22,C36159_SPMT,median market value of sales prices - middle tier,https://www.quandl.com/api/v3/datasets/ZILLOW/...
23,C36159_SPTT,median market value of sales prices - top tier,https://www.quandl.com/api/v3/datasets/ZILLOW/...
24,C36159_STLR,median market value of sale to list ratio,https://www.quandl.com/api/v3/datasets/ZILLOW/...
25,C4_HSAFRAL,median market value of home sold as foreclosu...,https://www.quandl.com/api/v3/datasets/ZILLOW/...
26,C4_MSPAH,median market value of median sold price - all...,https://www.quandl.com/api/v3/datasets/ZILLOW/...
27,C4_MSPFAH,median market value of median sold price per s...,https://www.quandl.com/api/v3/datasets/ZILLOW/...
28,C4_MSPFCO,median market value of median sold price per s...,https://www.quandl.com/api/v3/datasets/ZILLOW/...
29,C4_MSPFSF,median market value of median sold price per s...,https://www.quandl.com/api/v3/datasets/ZILLOW/...
30,C4_PTPFHAH,median market value of percent transactions th...,https://www.quandl.com/api/v3/datasets/ZILLOW/...
31,C4_TURNAH,median market value of turnover - all homes,https://www.quandl.com/api/v3/datasets/ZILLOW/...
32,C4_USRAH,median market value of unsold renos - all homes,https://www.quandl.com/api/v3/datasets/ZILLOW/...

In [4]:
#Get Data
urls = codesdf["url"]
datasets = []
for url in urls:
    response = requests.get(url).json()
    responsedf = pd.DataFrame(response)
    datasets.append(responsedf)

In [5]:
def get_dataset(index):
    code_value = codesdf["code"][index]
    code_label = codesdf["description"][index]
    data = quandl.get(f"ZILLOW/{code_value}", authtoken=api_key)
    data.reset_index(level=0, inplace=True)
    data["Code"]= code_value
    data["Label"] = code_label
    return data

In [6]:
num_codes = len(codesdf)
print(f"Number of datasets: {num_codes}")
#Get first dataset
data = get_dataset(0)
data.head()

Number of datasets: 33

,Date,Value,Code,Label
0,2010-11-30,5.31,C36159_BSICG,median market value of buyer seller index cross
1,2010-12-31,6.25,C36159_BSICG,median market value of buyer seller index cross
2,2011-01-31,6.88,C36159_BSICG,median market value of buyer seller index cross
3,2011-02-28,6.88,C36159_BSICG,median market value of buyer seller index cross
4,2011-03-31,6.56,C36159_BSICG,median market value of buyer seller index cross

In [7]:
#Append remaining datasets
for code_index in range(1,num_codes):
    new_data = get_dataset(code_index)
    #print(new_data)
    data = data.append(new_data)
    print(f"{code_index}: {codesdf['code'][code_index]} {len(new_data)} {len(data)}")

1: C36159_BSICT 106 212
2: C36159_DOZ 115 327
3: C36159_FOR10K 130 457
4: C36159_MDLNSAH 80 537
5: C36159_MDLSAAH 80 617
6: C36159_MLNSAH 80 697
7: C36159_MLSAAH 80 777
8: C36159_MTURN 128 905
9: C36159_NMLNSAH 80 985
10: C36159_NMLSAAH 80 1065
11: C36159_SC 138 1203
12: C36159_SCBT 138 1341
13: C36159_SCMT 138 1479
14: C36159_SCSA 138 1617
15: C36159_SCSABT 138 1755
16: C36159_SCSAMT 138 1893
17: C36159_SCSATT 138 2031
18: C36159_SCTT 138 2169
19: C36159_SP 138 2307
20: C36159_SPBT 138 2445
21: C36159_SPFS 122 2567
22: C36159_SPMT 138 2705
23: C36159_SPTT 138 2843
24: C36159_STLR 115 2958
25: C4_HSAFRAL 236 3194
26: C4_MSPAH 243 3437
27: C4_MSPFAH 255 3692
28: C4_MSPFCO 244 3936
29: C4_MSPFSF 244 4180
30: C4_PTPFHAH 236 4416
31: C4_TURNAH 236 4652
32: C4_USRAH 122 4774

In [63]:
#Export Data
data.to_csv("Zillow_data.csv")

In [8]:
data_pivot = data.pivot_table(index="Date",columns=["Code"],values=["Value"],aggfunc='mean')
data_pivot

                  Value                                                       \
Code       C36159_BSICG C36159_BSICT C36159_DOZ C36159_FOR10K C36159_MDLNSAH
Date
1996-04-30          NaN          NaN        NaN           NaN            NaN
1996-05-31          NaN          NaN        NaN           NaN            NaN
1996-06-30          NaN          NaN        NaN           NaN            NaN
1996-07-31          NaN          NaN        NaN           NaN            NaN
1996-08-31          NaN          NaN        NaN           NaN            NaN
1996-09-30          NaN          NaN        NaN           NaN            NaN
1996-10-31          NaN          NaN        NaN           NaN            NaN
1996-11-30          NaN          NaN        NaN           NaN            NaN
1996-12-31          NaN          NaN        NaN           NaN            NaN
1997-01-31          NaN          NaN        NaN           NaN            NaN
1997-02-28          NaN          NaN        NaN           NaN            NaN
1997-03-31          NaN          NaN        NaN           NaN            NaN
1997-04-30          NaN          NaN        NaN           NaN            NaN
1997-05-31          NaN          NaN        NaN           NaN            NaN
1997-06-30          NaN          NaN        NaN           NaN            NaN
1997-07-31          NaN          NaN        NaN           NaN            NaN
1997-08-31          NaN          NaN        NaN           NaN            NaN
1997-09-30          NaN          NaN        NaN           NaN            NaN
1997-10-31          NaN          NaN        NaN           NaN            NaN
1997-11-30          NaN          NaN        NaN           NaN            NaN
1997-12-31          NaN          NaN        NaN           NaN            NaN
1998-01-31          NaN          NaN        NaN           NaN            NaN
1998-02-28          NaN          NaN        NaN           NaN            NaN
1998-03-31          NaN          NaN        NaN           NaN            NaN
1998-04-30          NaN          NaN        NaN           NaN            NaN
1998-05-31          NaN          NaN        NaN           NaN            NaN
1998-06-30          NaN          NaN        NaN           NaN            NaN
1998-07-31          NaN          NaN        NaN           NaN            NaN
1998-08-31          NaN          NaN        NaN           NaN            NaN
1998-09-30          NaN          NaN        NaN           NaN            NaN
...                 ...          ...        ...           ...            ...
2017-03-31         6.25         4.25       63.0          0.62         5607.0
2017-04-30         6.25         4.34       64.0          0.46         5600.0
2017-05-31         6.25         4.53       63.0          0.46         5514.0
2017-06-30         5.62         4.62       63.0          0.41         5298.0
2017-07-31         5.62         4.91       63.0          0.41         5263.0
2017-08-31         5.62         5.00       62.0          0.72         5156.0
2017-09-30         5.62         5.57       63.0          0.50         5190.0
2017-10-31         5.62         5.75       64.0          0.72         5288.0
2017-11-30         5.94         6.13       64.0          1.31         5378.0
2017-12-31         5.62         6.42       66.0          0.76         5066.0
2018-01-31         5.94         6.70       77.0          0.62         4863.0
2018-02-28         5.94         7.83       71.0          0.72         5131.0
2018-03-31         6.25         8.87       57.0          0.69         5212.0
2018-04-30         5.94         9.62       54.0          0.38         5341.0
2018-05-31         5.94         9.81       55.0          0.43         5332.0
2018-06-30         5.94         9.91       55.0          0.29         5282.0
2018-07-31         5.62         9.72       57.0          0.55         5145.0
2018-08-31         6.25         9.43       57.0          0.41         5035.0
2018-09-30         5.94         9.06       60.0          0.26         5027.0
2018-10-31         5.94         8.96       60.0          0.38         5185.0
2018-11-30         5.94         8.58       60.0           NaN         5372.0
2018-12-31         5.94         8.77       63.0           NaN         5110.0
2019-01-31         5.62         8.30       75.0           NaN         5232.0
2019-02-28         5.94         7.92       72.0           NaN         5656.0
2019-03-31         6.25         7.08       61.0           NaN         5666.0
2019-04-30         6.56         6.89       61.0           NaN         5673.0
2019-05-31         5.94         7.45       57.0           NaN         5272.0
2019-06-30         5.94         8.49       59.0           NaN         4923.0
2019-07-31         5.94         9.34       59.0           NaN         4588.0
2019-08-31         5.62        10.00        NaN           NaN         4217.0

                                                                    \
Code       C36159_MDLSAAH C36159_MLNSAH C36159_MLSAAH C36159_MTURN
Date
1996-04-30            NaN           NaN           NaN          NaN
1996-05-31            NaN           NaN           NaN          NaN
1996-06-30            NaN           NaN           NaN          NaN
1996-07-31            NaN           NaN           NaN          NaN
1996-08-31            NaN           NaN           NaN          NaN
1996-09-30            NaN           NaN           NaN          NaN
1996-10-31            NaN           NaN           NaN          NaN
1996-11-30            NaN           NaN           NaN          NaN
1996-12-31            NaN           NaN           NaN          NaN
1997-01-31            NaN           NaN           NaN          NaN
1997-02-28            NaN           NaN           NaN          NaN
1997-03-31            NaN           NaN           NaN          NaN
1997-04-30            NaN           NaN           NaN          NaN
1997-05-31            NaN           NaN           NaN          NaN
1997-06-30            NaN           NaN           NaN          NaN
1997-07-31            NaN           NaN           NaN          NaN
1997-08-31            NaN           NaN           NaN          NaN
1997-09-30            NaN           NaN           NaN          NaN
1997-10-31            NaN           NaN           NaN          NaN
1997-11-30            NaN           NaN           NaN          NaN
1997-12-31            NaN           NaN           NaN          NaN
1998-01-31            NaN           NaN           NaN          NaN
1998-02-28            NaN           NaN           NaN          NaN
1998-03-31            NaN           NaN           NaN          NaN
1998-04-30            NaN           NaN           NaN          NaN
1998-05-31            NaN           NaN           NaN          NaN
1998-06-30            NaN           NaN           NaN          NaN
1998-07-31            NaN           NaN           NaN          NaN
1998-08-31            NaN           NaN           NaN          NaN
1998-09-30            NaN           NaN           NaN          NaN
...                   ...           ...           ...          ...
2017-03-31         5496.0        8191.0        7656.0       0.0079
2017-04-30         5465.0        7551.0        7478.0       0.0070
2017-05-31         5392.0        7958.0        7370.0       0.0086
2017-06-30         5354.0        7153.0        7237.0       0.0085
2017-07-31         5381.0        7046.0        7239.0       0.0068
2017-08-31         5384.0        7372.0        7338.0       0.0076
2017-09-30         5302.0        6847.0        7136.0       0.0068
2017-10-31         5185.0        6918.0        7018.0       0.0072
2017-11-30         5143.0        7390.0        7102.0       0.0063
2017-12-31         5138.0        6341.0        7074.0       0.0070
2018-01-31         5087.0        7042.0        7052.0       0.0059
2018-02-28         5059.0        6958.0        6953.0       0.0068
2018-03-31         5115.0        7013.0        6822.0       0.0078
2018-04-30         5184.0        7234.0        6962.0       0.0079
2018-05-31         5225.0        7734.0        7160.0       0.0082
2018-06-30         5266.0        7129.0        7104.0       0.0081
2018-07-31         5287.0        6812.0        7068.0       0.0079
2018-08-31         5255.0        7175.0        7142.0       0.0076
2018-09-30         5165.0        6687.0        7100.0       0.0060
2018-10-31         5094.0        7287.0        7004.0       0.0069
2018-11-30         5130.0        6737.0        6883.0          NaN
2018-12-31         5257.0        6376.0        7008.0          NaN
2019-01-31         5418.0        7329.0        7304.0          NaN
2019-02-28         5529.0        7333.0        7360.0          NaN
2019-03-31         5553.0        7610.0        7307.0          NaN
2019-04-30         5441.0        7621.0        7318.0          NaN
2019-05-31         5181.0        7809.0        7186.0          NaN
2019-06-30         4928.0        6743.0        6865.0          NaN
2019-07-31         4714.0        6582.0        6523.0          NaN
2019-08-31         4543.0        5833.0        6223.0          NaN

                           ...                                                \
Code       C36159_NMLNSAH  ... C36159_SPTT C36159_STLR C4_HSAFRAL   C4_MSPAH
Date                       ...
1996-04-30            NaN  ...         NaN         NaN        NaN   90733.30
1996-05-31            NaN  ...         NaN         NaN        NaN   88950.00
1996-06-30            NaN  ...         NaN         NaN        NaN   90050.00
1996-07-31            NaN  ...         NaN         NaN        NaN   90991.50
1996-08-31            NaN  ...         NaN         NaN        NaN   91766.55
1996-09-30            NaN  ...         NaN         NaN        NaN   89899.95
1996-10-31            NaN  ...         NaN         NaN        NaN   89100.00
1996-11-30            NaN  ...         NaN         NaN        NaN   90251.00
1996-12-31            NaN  ...         NaN         NaN        NaN   89980.70
1997-01-31            NaN  ...         NaN         NaN        NaN   89825.80
1997-02-28            NaN  ...         NaN         NaN        NaN   91033.85
1997-03-31            NaN  ...         NaN         NaN        NaN   92346.65
1997-04-30            NaN  ...         NaN         NaN        NaN   92925.00
1997-05-31            NaN  ...         NaN         NaN        NaN   93500.00
1997-06-30            NaN  ...         NaN         NaN        NaN   94349.50
1997-07-31            NaN  ...         NaN         NaN        NaN   94599.65
1997-08-31            NaN  ...         NaN         NaN        NaN   94824.85
1997-09-30            NaN  ...         NaN         NaN        NaN   95425.00
1997-10-31            NaN  ...         NaN         NaN        NaN   95300.00
1997-11-30            NaN  ...         NaN         NaN        NaN   96115.00
1997-12-31            NaN  ...         NaN         NaN        NaN   98635.00
1998-01-31            NaN  ...         NaN         NaN     2.7046   99315.00
1998-02-28            NaN  ...         NaN         NaN     2.5525   99970.00
1998-03-31            NaN  ...         NaN         NaN     2.3472  101239.00
1998-04-30            NaN  ...         NaN         NaN     2.5338  101241.00
1998-05-31            NaN  ...         NaN         NaN     2.6705  101585.00
1998-06-30            NaN  ...         NaN         NaN     3.2311  103790.00
1998-07-31            NaN  ...         NaN         NaN     3.3434  104900.00
1998-08-31            NaN  ...         NaN         NaN     3.6993  106275.00
1998-09-30            NaN  ...         NaN         NaN     3.5761  105537.50
...                   ...  ...         ...         ...        ...        ...
2017-03-31         2489.0  ...    412300.0    0.973593     1.1772        NaN
2017-04-30         2485.0  ...    417000.0    0.975258     0.8202        NaN
2017-05-31         2503.0  ...    427300.0    0.975494     0.5184        NaN
2017-06-30         2192.0  ...    425400.0    0.976986     0.3565        NaN
2017-07-31         1814.0  ...    427400.0    0.975000     0.4270        NaN
2017-08-31         2150.0  ...    423600.0    0.976471     0.4927        NaN
2017-09-30         1958.0  ...    424400.0    0.972644        NaN        NaN
2017-10-31         1818.0  ...    423200.0    0.974196        NaN        NaN
2017-11-30         1872.0  ...    430100.0    0.970588        NaN        NaN
2017-12-31         1321.0  ...    438700.0    0.967732        NaN        NaN
2018-01-31         2352.0  ...    453700.0    0.971429        NaN        NaN
2018-02-28         2308.0  ...    458100.0    0.974026        NaN        NaN
2018-03-31         2388.0  ...    456600.0    0.978462        NaN        NaN
2018-04-30         2123.0  ...    447500.0    0.981132        NaN        NaN
2018-05-31         2487.0  ...    445400.0    0.982143        NaN        NaN
2018-06-30         2207.0  ...    448500.0    0.980707        NaN        NaN
2018-07-31         1731.0  ...    462200.0    0.982456        NaN        NaN
2018-08-31         2077.0  ...    469200.0    0.977591        NaN        NaN
2018-09-30         1790.0  ...    468300.0    0.973451        NaN        NaN
2018-10-31         2242.0  ...    470200.0    0.974441        NaN        NaN
2018-11-30         1790.0  ...    480700.0    0.973329        NaN        NaN
2018-12-31         1263.0  ...    483200.0    0.972602        NaN        NaN
2019-01-31         2296.0  ...    475400.0    0.969356        NaN        NaN
2019-02-28         2051.0  ...    468400.0    0.970339        NaN        NaN
2019-03-31         2299.0  ...    477400.0    0.974952        NaN        NaN
2019-04-30         2028.0  ...    485100.0    0.975307        NaN        NaN
2019-05-31         2124.0  ...    489400.0    0.979996        NaN        NaN
2019-06-30         1798.0  ...    489900.0    0.979818        NaN        NaN
2019-07-31         1949.0  ...    485300.0    0.980049        NaN        NaN
2019-08-31         1851.0  ...    477500.0         NaN        NaN        NaN


Code       C4_MSPFAH C4_MSPFCO C4_MSPFSF C4_PTPFHAH C4_TURNAH C4_USRAH
Date
1996-04-30   62.5223   58.1028   63.1525        NaN       NaN      NaN
1996-05-31   62.0292   56.0882   62.9386        NaN       NaN      NaN
1996-06-30   62.3889   55.2674   63.2970        NaN       NaN      NaN
1996-07-31   62.5243   55.4199   63.3648        NaN       NaN      NaN
1996-08-31   62.9794   57.1134   63.6982        NaN       NaN      NaN
1996-09-30   63.1994   56.8783   63.8872        NaN       NaN      NaN
1996-10-31   63.0577   57.2081   63.7903        NaN       NaN      NaN
1996-11-30   63.7293   56.7640   64.7672        NaN       NaN      NaN
1996-12-31   63.9730   58.4204   64.7921        NaN       NaN      NaN
1997-01-31   63.9219   58.4668   64.6948        NaN       NaN      NaN
1997-02-28   64.0928   59.1305   64.8083        NaN       NaN      NaN
1997-03-31   64.3705   59.9563   64.9230        NaN       NaN      NaN
1997-04-30   65.0241   61.6991   65.3394        NaN       NaN      NaN
1997-05-31   65.5834   62.5956   66.0855        NaN       NaN      NaN
1997-06-30   66.2299   61.5574   66.8010        NaN       NaN      NaN
1997-07-31   66.3044   61.2322   66.9501        NaN       NaN      NaN
1997-08-31   66.4257   60.4102   67.0901        NaN       NaN      NaN
1997-09-30   66.7259   59.9498   67.6614        NaN       NaN      NaN
1997-10-31   66.7723   58.7311   67.9431        NaN       NaN      NaN
1997-11-30   66.6353   60.3252   67.6744        NaN       NaN      NaN
1997-12-31   67.2737   62.2826   67.9167        NaN       NaN      NaN
1998-01-31   68.1133   63.9050   69.0314     2.3006    7.0250      NaN
1998-02-28   69.0909   64.2549   69.8082     2.0896    7.0426      NaN
1998-03-31   69.4684   64.6169   70.2186     1.9766    7.0847      NaN
1998-04-30   69.9419   64.5951   70.5484     1.9204    7.1243      NaN
1998-05-31   70.2850   64.6273   71.2318     1.9154    7.1209      NaN
1998-06-30   70.7956   65.2384   71.8155     1.7525    7.1840      NaN
1998-07-31   71.2072   65.9179   71.9988     1.7391    7.2317      NaN
1998-08-31   71.1080   65.0411   72.0170     1.9805    7.2621      NaN
1998-09-30   71.3907   63.8890   72.3301     2.3402    7.2904      NaN
...              ...       ...       ...        ...       ...      ...
2017-03-31  138.0000       NaN       NaN     6.3915    6.5234      NaN
2017-04-30  139.0000       NaN       NaN     6.3360    6.2974      NaN
2017-05-31  140.0000       NaN       NaN     5.6575    6.1310      NaN
2017-06-30  141.0000       NaN       NaN     5.6756    6.0805      NaN
2017-07-31       NaN       NaN       NaN     5.7281    6.0812      NaN
2017-08-31       NaN       NaN       NaN     5.9816    6.1026      NaN
2017-09-30       NaN       NaN       NaN        NaN       NaN      NaN
2017-10-31       NaN       NaN       NaN        NaN       NaN      NaN
2017-11-30       NaN       NaN       NaN        NaN       NaN      NaN
2017-12-31       NaN       NaN       NaN        NaN       NaN      NaN
2018-01-31       NaN       NaN       NaN        NaN       NaN      NaN
2018-02-28       NaN       NaN       NaN        NaN       NaN      NaN
2018-03-31       NaN       NaN       NaN        NaN       NaN      NaN
2018-04-30       NaN       NaN       NaN        NaN       NaN      NaN
2018-05-31       NaN       NaN       NaN        NaN       NaN      NaN
2018-06-30       NaN       NaN       NaN        NaN       NaN      NaN
2018-07-31       NaN       NaN       NaN        NaN       NaN      NaN
2018-08-31       NaN       NaN       NaN        NaN       NaN      NaN
2018-09-30       NaN       NaN       NaN        NaN       NaN      NaN
2018-10-31       NaN       NaN       NaN        NaN       NaN      NaN
2018-11-30       NaN       NaN       NaN        NaN       NaN      NaN
2018-12-31       NaN       NaN       NaN        NaN       NaN      NaN
2019-01-31       NaN       NaN       NaN        NaN       NaN      NaN
2019-02-28       NaN       NaN       NaN        NaN       NaN      NaN
2019-03-31       NaN       NaN       NaN        NaN       NaN      NaN
2019-04-30       NaN       NaN       NaN        NaN       NaN      NaN
2019-05-31       NaN       NaN       NaN        NaN       NaN      NaN
2019-06-30       NaN       NaN       NaN        NaN       NaN      NaN
2019-07-31       NaN       NaN       NaN        NaN       NaN      NaN
2019-08-31       NaN       NaN       NaN        NaN       NaN      NaN

[281 rows x 33 columns]

In [9]:
data_pivot.to_csv("Zillow_pivot.csv")

Data cleaned manually to fix headers